# Very simple plugin to use. If you need any help dm me on discord @Erosion#2069
466-cooldown: 40 # Cooldown timer in seconds 
466-message: "§6» §7Enchanted Golden Apple is on cooldown for {466-cooldown}s" # Cooldown message

