# ╔═══╗─────────────╔╗──╔╦════╗
# ║╔══╝─────────────║╚╗╔╝║╔╗╔╗║
# ║╚══╦═╦══╦══╦╦══╦═╬╗╚╝╔╩╝║║╚╝
# ║╔══╣╔╣╔╗║══╬╣╔╗║╔╗╬╗╔╝──║║
# ║╚══╣║║╚╝╠══║║╚╝║║║║║║───║║
# ╚═══╩╝╚══╩══╩╩══╩╝╚╝╚╝───╚╝
# Very simple plugin to use. If you need any help dm me on discord @Erosion#2069
cooldown: 40 # Cooldown timer in seconds 
message: "[§6eCooldown§f] §7Enchanted Golden Apple is on cooldown for {cooldown}s" # Cooldown message

